resources:
- name: github-repo
  type: git
  source:
    uri: https://github.com/ONSdigital/census-worth-self-help.git
    branch: master

jobs:
- name: test
  plan:
  - get: github-repo
    trigger: true
  - task: unit test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
          tag: alpine
        
      inputs:
      - name: github-repo

      caches:
      - path: github-repo/site/node_modules

      run:
        path: sh
        args:
        - -exec
        - |
            cd github-repo/site
            npm install
            npm run test

- name: build
  plan:
  - get: github-repo
    passed: [test]
    trigger: true
  - task: a
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
          tag: alpine
    
      inputs:
      - name: github-repo

      outputs:
      - name: public

      caches:
      - path: github-repo/site/node_modules

      run:
        path: sh
        args:
        - -exec
        - |
            cd github-repo/site
            npm install
            npm run build