resources:
- name: github-repo
  type: git
  source:
    uri: https://github.com/ONSdigital/census-worth-self-help.git
    branch: feature/ONS-12-pipeline-to-build-and-deploy-to-dev-env

jobs:
- name: build
  plan:
  - get: github-repo
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
          tag: alpine
    
      inputs:
      - name: github-repo

      outputs:
      - name: public

      caches:
      - path: github-repo/site/node_modules

      run:
        path: sh
        args:
        - -exec
        - |
            ls
            cd github-repo/site
            ls
            npm install
            BUILD="_build/content/"
            mkdir -p "$BUILD" && cp -R ../content/ "$BUILD"
            npm run build