resources:
  - name: census-worth-self-help
    type: git
    source:
      uri: https://github.com/ONSdigital/census-worth-self-help.git
      branch: feature/ONS-148-generate-dev-report
    webhook_token: ((git.census-worth-self-help-webhook-token))
    check_every: 24h

jobs:
  - name: report
    plan:
      - get: census-worth-self-help
        trigger: true
      - task: e2e-test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cypress/base
              tag: 10

          inputs:
            - name: census-worth-self-help

          outputs:
            - name: mochaawesome-report

          caches:
            - path: .npm
            - path: .cypress-cache

          run:
            path: sh
            args:
              - -exec
              - |
                export ROOT_FOLDER=$(pwd)
                export CYPRESS_CACHE_FOLDER=${ROOT_FOLDER}/.cypress-cache
                cd census-worth-self-help/site
                npm ci
                npm test
                ./localbuild.sh
                npm run e2e
                mv census-worth-self-help/site/mochaawesome-report ../../mochaawesome-report

      - task: deploy
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: google/cloud-sdk
              tag: alpine

          params:
            AUTH_KEY: ((gcp.service-account-key))
            PROJECT: ((gcp.project-name))
            GCP_SECRETS_VERSION: ((gcp.secrets-version))

          inputs:
            - name: census-worth-self-help
            - name: mochaawesome-report

          caches:
            - path: census-worth-self-help/site/node_modules

          run:
            path: sh
            args:
              - -exec
              - |
                set +x
                echo "GCP Secrets Version      : $GCP_SECRETS_VERSION"
                set -x
                apk add --no-progress --update nodejs nodejs-npm
                cd census-worth-self-help/site
                npm install
                BUILD="_build/content/"
                mkdir -p "$BUILD"
                cp -R ../content/ "$BUILD"
                npm run coverage

                cd ../report
                mkdir -p public
                cp -R static/* public/
                cp -R ../site/coverage public/
                cp -R ../../mochaawesome-report public/
                set +x
                echo $AUTH_KEY > encrypted_key.txt
                set -x
                base64 -d encrypted_key.txt > service-account.json
                gcloud auth activate-service-account --key-file service-account.json
                gcloud config set project $PROJECT
                gcloud app deploy -q