resources:
  - name: census-worth-self-help
    type: git
    source:
      uri: https://github.com/ONSdigital/census-worth-self-help.git
      branch: feature/ONS-9-saml-2
    check_every: 15m

  - name: content-repository
    type: git
    source:
      uri: git@github.com:ONSdigital/census-worth-self-help.git
      branch: master

jobs:
  - name: deploy
    plan:
      - get: census-worth-self-help
        trigger: true
      - get: content-repository
      - task: deploy
        params:
          SERVICE: secured
          BUILD_NETLIFY: false
          BACKEND_CONTENT_REPO: census-worth-self-help-test
        file: census-worth-self-help/pipeline/tasks/deploy-site.yml