resources:
  - name: after-midnight
    type: time
    source:
      start: 12:00 AM
      stop: 1:00 AM

  - name: census-worth-self-help
    type: git
    source:
      uri: https://github.com/ONSdigital/census-worth-self-help.git
      branch: master

  - name: content-repository
    type: git
    source:
      uri: https://github.com/ONSdigital/census-worth-self-help.git
      branch: master
jobs:
  - name: dev
    build_log_retention:
      days: 7
      builds: 10
    max_in_flight: 1
    plan:
      - get: after-midnight
        trigger: true
      - get: census-worth-self-help
      - get: content-repository
      - task: deploy
        file: census-worth-self-help/pipeline/tasks/deploy-site.yml
        params:
          BACKEND_CONTENT_REPO: census-worth-self-help
          DISABLE_NETLIFY: false
          ENABLE_MATOMO: true
          GCP_SECRETS_VERSION: ((gcp.secrets-version))
          MATOMO_IP: ((matomo.matomo-ip-address))
          MATOMO_SITE_ID: 2
          MATOMO_URL: ((matomo.matomo-site-url))
          PATCH_NETLIFY: true
          PROJECT: ((gcp.project-name))
          SERVICE: default
          SP_PROTECTED: false
          GATSBY_ASSETS_PATH: ((gatsby.assets-path))
          GATSBY_CHAT_BUTTON_CONTAINER_ID: ((gatsby.chat-button-container-id))
          GATSBY_CHAT_CHANNEL: ((gatsby.chat-channel))
          GATSBY_CHAT_DOMAIN: ((gatsby.chat-domain))
          GATSBY_CHAT_TENANT: ((gatsby.chat-tenant))
          GATSBY_CHAT_UUID: ((gatsby.chat-uuid))