
jobs:
- name: deploy
  plan:
  - get: census-worth-self-help
    trigger: true
  - get: content-repository
    trigger: true
  
  - task: deploy
    params:
      SERVICE: testbeta
      BUILD_NETLIFY: false     
      BACKEND_CONTENT_REPO: census-worth-self-help-test
    file: census-worth-self-help/pipeline/tasks/deploy-site.yml