resources:
- name: census-worth-self-help
  type: git
  source:
    uri: https://github.com/ONSdigital/census-worth-self-help.git
    branch: master
  check_every: 15m

- name: content-repository
  type: git
  source:
    uri: git@github.com:ONSdigital/census-worth-self-help-test.git
    branch: master
    private_key: ((git-keys-test.private-key))
  webhook_token: ((git.census-worth-self-help-test-webhook-token))

jobs:
- name: deploy
  plan:
  - get: census-worth-self-help
    trigger: true
  - get: content-repository
    trigger: true
  
  - task: deploy
    params:
      SERVICE: test
      BUILD_NETLIFY: false     
      BACKEND_CONTENT_REPO: census-worth-self-help-test
    file: census-worth-self-help/pipeline/tasks/deploy-site.yml