resources:
  - name: github-site-code
    type: git
    source:
      uri: https://github.com/ONSdigital/census-worth-self-help.git
      branch: feature/ONS-13-add-new-trigger-pipeline
    webhook_token: code-trigger
    
  - name: github-site-content
    type: git
    source:
      uri: git@github.com:ONSdigital/census-worth-self-help-content.git
      branch: master
      private_key: ((git-keys.private-key))
    webhook_token: content-trigger

  - name: census-worth-self-help-test
    type: git
    source:
      uri: git@github.com:ONSdigital/census-worth-self-help-test.git
      branch: master
      private_key: ((git-test-keys.private-key))
    webhook_token: test-content-trigger
    check_every: 5m

jobs:
  - name: deploy
    plan:
      - get: github-site-code
      - get: github-site-content
      - get: census-worth-self-help-test
        trigger: true

      - task: deploy
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: google/cloud-sdk
              tag: alpine

          params:
            GCP_SECRETS_VERSION : ((gcp.secrets-version))
            GIT_SECRETS_VERSION : ((git-keys.secrets-version))

          caches:
            - path: $HOME/.npm

          inputs:
            - name: github-site-code
            - name: github-site-content

          run:
            path: sh
            args:
              - -exec
              - |
                echo "GCP Secrets Version : $GCP_SECRETS_VERSION"
                echo "Git Secrets Version : $GIT_SECRETS_VERSION"