resources:
- name: census-worth-self-help
  type: git
  source:
    uri: https://github.com/ONSdigital/census-worth-self-help.git
    branch: master
  webhook_token: ((git.census-worth-self-help-webhook-token))
  check_every: 15m

- name: content-repository
  type: git
  source:
    uri: git@github.com:ONSdigital/census-worth-self-help-test.git
    branch: master
    private_key: ((git-keys-test.private-key))
  webhook_token: ((git.census-worth-self-help-test-webhook-token))
  check_every: 5m

- name: timer
  type: time
  icon: clock-outline
  source:
    interval: 60m

jobs:
- name: test
  plan:

  - get: timer
  - get: census-worth-self-help

  - task: test
    file: census-worth-self-help/pipeline/tasks/test.yml

  - task: deploy-reports
    file: census-worth-self-help/pipeline/tasks/deploy-test-reports.yml

- name: deploy
  plan:
  - get: census-worth-self-help
    trigger: true
    passed:
    - test

  - get: content-repository
    trigger: true

  - task: deploy
    params:
      SERVICE: default
      BUILD_NETLIFY: false     
      BACKEND_CONTENT_REPO: census-worth-self-help-test
    file: census-worth-self-help/pipeline/tasks/deploy-site.yml