resources:
  - name: census-worth-self-help
    type: git
    source:
      uri: https://github.com/ONSdigital/census-worth-self-help.git
      branch: v1.11.1

  - name: census-worth-self-help-content
    type: git
    source:
      uri: git@github.com:ONSdigital/census-worth-self-help-content.git
      branch: master
      private_key: ((git-keys.private-key))
    webhook_token: ((git.census-worth-self-help-content-webhook-token))

jobs:
  - name: deploy
    plan:
      - get: census-worth-self-help
      - get: census-worth-self-help-content
        trigger: true

      - task: deploy
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: google/cloud-sdk
              tag: alpine

          params:
            AUTH_KEY: ((gcp.service-account-key))
            PROJECT: ((gcp.project-name))
            GCP_SECRETS_VERSION: ((gcp.secrets-version))

          caches:
            - path: census-worth-self-help/site/node_modules

          inputs:
            - name: census-worth-self-help
            - name: census-worth-self-help-content

          run:
            path: sh
            args:
              - -exec
              - |
                echo "GCP Secrets Version : $GCP_SECRETS_VERSION"
                apk add --no-progress --update nodejs nodejs-npm
                echo "npm version"
                npm -v
                cd census-worth-self-help/site
                npm install
                BUILD="_build/content/"
                mkdir -p "$BUILD" && cp -R ../../census-worth-self-help-content/content/ "$BUILD"
                ASSET_DIR="static/assets/"
                cp -R ../../census-worth-self-help-content/static/assets "$ASSET_DIR"
                npm run build
                set +x
                echo $AUTH_KEY > encrypted_key.txt
                set -x
                base64 -d encrypted_key.txt > service-account.json
                gcloud auth activate-service-account --key-file service-account.json
                gcloud config set project $PROJECT
                sed "s/service:.*/service: cms/" app.yaml > ci-app.yaml
                sed -i "s/  branch:.*/  branch: master/" public/admin/config.yml
                sed -i "s/  repo:.*/  repo: ONSdigital\/census-worth-self-help-content/" public/admin/config.yml
                gcloud app deploy -q ci-app.yaml