resources:
  - name: census-worth-self-help
    type: git
    source:
      uri: https://github.com/ONSdigital/census-worth-self-help.git
      branch: bugfix/ONS-264-visual-alert-for-deployment
    check_every: 15m

  - name: content-repository
    type: git
    source:
      uri: https://github.com/ONSdigital/census-worth-self-help.git
      branch: master

jobs:
  - name: protected
    build_log_retention:
      days: 7
      builds: 10
    plan:
      - get: census-worth-self-help
        trigger: true
      - get: content-repository
      - task: deploy
        file: census-worth-self-help/pipeline/tasks/deploy-site.yml
        params:
          BACKEND_CONTENT_REPO: census-worth-self-help
          PATCH_NETLIFY: false
          COOKIE_SECRET: ((sso.cookie-secret))
          ENABLE_MATOMO: true
          IDP_ENTRY_POINT: ((sso.idp-entry-point))
          IDP_LOGOUT: ((sso.idp-logout))
          IDP_CERTIFICATE: ((sso.idp-certificate))
          INJECT_DEPLOYMENT_INFORMATION: true
          MATOMO_IP: ((matomo.matomo-ip-address))
          MATOMO_SITE_ID: 8
          MATOMO_URL: ((matomo.matomo-site-url))
          PROJECT: ((gcp.project-name-live))
          SERVICE: default
          SP_CERTIFICATE: ((sso.sp-certificate))
          SP_DOMAIN_NAME: secured.((dns.default-domain))
          SP_KEY: ((sso.sp-key))
          SP_PROTECTED: true