resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
  - name: census-worth-self-help
    type: git
    source:
      uri: https://github.com/ONSdigital/census-worth-self-help.git
      branch: feature/ONS-195-concourse-slack-integration
    webhook_token: ((git.census-worth-self-help-webhook-token))
    check_every: 24h

  - name: slack-notify
    type: slack-notification
    source:
      url: https://hooks.slack.com/services/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

jobs:
  - name: report
    build_log_retention:
      days: 7
      builds: 10
    plan:
      - get: census-worth-self-help
        trigger: true
      - task: test
        file: census-worth-self-help/pipeline/tasks/test.yml

        on_failure:
          do:
          - task: get-slack-env-vars
            file: census-worth-self-help/pipeline/tasks/slack-env-vars.yml

          - put: slack-notify
            params:
              env_file: env_file/.env
              text: |
                Test failed! :x:
                Build logs: $CI_URL/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
                Report: $REPORT_URL

        ensure:
          task: deploy-reports
          file: census-worth-self-help/pipeline/tasks/deploy-test-reports.yml