resources:
  - name: census-worth-self-help
    type: git
    source:
      uri: https://github.com/ONSdigital/census-worth-self-help.git
      branch: feature/ONS-575-make-colour-modifiable-across-aspects-of-site
    check_every: 15m

  - name: content-repository
    type: git
    source:
      uri: git@github.com:ONSdigital/census-worth-self-help-test.git
      branch: master
      private_key: ((git-keys-test.private-key))
    webhook_token: ((git.census-worth-self-help-test-webhook-token))

jobs:
  - name: deploy
    build_log_retention:
      days: 8
      builds: 10
    max_in_flight: 1
    plan:
      - get: census-worth-self-help
      - get: content-repository
        trigger: true

      - task: deploy
        params:
          BACKEND_CONTENT_REPO: census-worth-self-help-test
          ENABLE_MATOMO: true
          EXCLUDE_DRAFTS: 'true'
          MATOMO_IP: ((matomo.matomo-ip-address))
          MATOMO_SITE_ID: 8
          PATCH_NETLIFY: true
          PROJECT: ((gcp.project-name))
          SERVICE: test
          SKIP_UNIT_TESTS: true
          SKIP_AUDIT: true
          SP_PROTECTED: false
          GATSBY_SITE_COLOUR: primary
        file: census-worth-self-help/pipeline/tasks/deploy-site.yml
