resources:
  - name: census-worth-self-help
    type: git
    source:
      uri: https://github.com/ONSdigital/census-worth-self-help.git
      branch: master
    webhook_token: ((git.census-worth-self-help-webhook-token))
    check_every: 24h

jobs:
  - name: report
    build_log_retention:
      days: 7
      builds: 10
    plan:
      - get: census-worth-self-help
        trigger: true
      - task: e2e-test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cypress/base
              tag: 10

          inputs:
            - name: census-worth-self-help

          outputs:
            - name: mochawesome-report
              path: census-worth-self-help/site/mochawesome-report
            - name: coverage
              path: census-worth-self-help/site/coverage

          caches:
            - path: .npm
            - path: .cypress-cache

          run:
            path: sh
            args:
              - -exec
              - |
                export ROOT_FOLDER=$(pwd)
                export CYPRESS_CACHE_FOLDER=${ROOT_FOLDER}/.cypress-cache
                cd census-worth-self-help/site
                npm ci
                npm test -- --coverage
                ./localbuild.sh
                npm run e2e

      - task: deploy
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: google/cloud-sdk
              tag: alpine

          params:
            AUTH_KEY: ((gcp.service-account-key))
            PROJECT: ((gcp.project-name))
            GCP_SECRETS_VERSION: ((gcp.secrets-version))

          inputs:
            - name: census-worth-self-help
            - name: mochawesome-report
              path: census-worth-self-help/site/mochawesome-report
            - name: coverage
              path: census-worth-self-help/site/coverage

          caches:
            - path: census-worth-self-help/site/node_modules

          run:
            path: sh
            args:
              - -exec
              - |
                cd census-worth-self-help/report
                mkdir -p public
                cp -R static/* public/
                cp -R ../site/coverage public/
                cp -R ../site/mochawesome-report public/
                set +x
                echo $AUTH_KEY > encrypted_key.txt
                set -x
                base64 -d encrypted_key.txt > service-account.json
                gcloud auth activate-service-account --key-file service-account.json
                gcloud config set project $PROJECT
                gcloud app deploy -q