resources:
  - name: census-worth-self-help
    type: git
    source:
      uri: https://github.com/ONSdigital/census-worth-self-help.git
      branch: master
    webhook_token: ((git.census-worth-self-help-webhook-token))
    check_every: 24h

jobs:
  - name: report
    build_log_retention:
      days: 7
      builds: 10
    plan:
      - get: census-worth-self-help
        trigger: true
      - task: test
        file: census-worth-self-help/pipeline/tasks/test.yml

      - task: deploy-reports
        file: census-worth-self-help/pipeline/tasks/deploy-test-reports.yml