resources:
  - name: census-worth-self-help
    type: git
    source:
      uri: https://github.com/ONSdigital/census-worth-self-help.git
      branch: master
    check_every: 15m

  - name: content-repository
    type: git
    source:
      uri: https://github.com/ONSdigital/census-worth-self-help-test.git
      branch: master

jobs:
  - name: protected
    build_log_retention:
      days: 7
      builds: 10
    max_in_flight: 1
    plan:
      - get: census-worth-self-help
        trigger: true
      - get: content-repository
      - task: deploy
        file: census-worth-self-help/pipeline/tasks/deploy-site.yml
        params:
          BACKEND_CONTENT_REPO: census-worth-self-help
          COOKIE_SECRET: ((sso.cookie-secret))
          COOKIE_TIMEOUT: 10
          DISABLE_NETLIFY: true
          ENABLE_MATOMO: true
          EXCLUDE_DRAFTS: 'true'
          IDP_ENTRY_POINT: ((sso.idp-entry-point))
          IDP_LOGOUT: ((sso.idp-logout))
          IDP_CERTIFICATE: ((sso.idp-certificate))
          INJECT_DEPLOYMENT_INFORMATION: true
          MATOMO_IP: ((matomo.matomo-ip-address))
          MATOMO_SITE_ID: 8
          MATOMO_URL: ((matomo.matomo-site-url))
          PATCH_NETLIFY: false
          PROJECT: ((gcp.project-name-live))
          SERVICE: default
          SP_CERTIFICATE: ((sso.sp-certificate))
          SP_DOMAIN_NAME: secured.((dns.default-domain))
          SP_KEY: ((sso.sp-key))
          SP_PROTECTED: true
          VALID_TOKEN_AGE: 4