resources:
  - name: census-worth-self-help
    type: git
    source:
      uri: https://github.com/ONSdigital/census-worth-self-help.git
      branch: master
    webhook_token: ((git.census-worth-self-help-webhook-token))
    check_every: 15m

  - name: content-repository
    type: git
    source:
      uri: https://github.com/ONSdigital/census-worth-self-help.git
      branch: master
jobs:
  - name: dev
    build_log_retention:
      days: 7
      builds: 10
    plan:
      - get: census-worth-self-help
        trigger: true
      - get: content-repository
      - task: deploy
        file: census-worth-self-help/pipeline/tasks/deploy-site.yml
        params:
          BACKEND_CONTENT_REPO: census-worth-self-help
          PATCH_NETLIFY: true
          GCP_SECRETS_VERSION: ((gcp.secrets-version))
          DISABLE_NETLIFY: true
          ENABLE_MATOMO: true
          MATOMO_IP: ((matomo.matomo-ip-address))
          MATOMO_SITE_ID: 2
          MATOMO_URL: ((matomo.matomo-site-url))
          PROJECT: ((gcp.project-name))
          SERVICE: default
          SP_PROTECTED: false