runtime: nodejs10
service: secured
default_expiration: "1m"
handlers:
  - url: /(.*\.json)
    mime_type: application/json
    static_files: public/\1
    upload: public/(.*\.json)

# Netlify CMS has a config.yml that needs to be served up
  - url: /(.*\.yml)
    mime_type: text/yaml
    static_files: public/\1
    upload: public/(.*\.yml)

  - url: /(.*\.js)
    mime_type: text/javascript
    static_files: public/\1
    upload: public/(.*\.js)

# Images and fonts
  - url: /(.*\.(gif|ico|jpeg|jpg|png|svg))
    static_files: public/\1
    upload: public/(.*\.(gif|ico|jpeg|jpg|png|svg))

# Fonts
  - url: /(.*\.(woff|woff2|tff|eot))
    static_files: public/\1
    upload: public/(.*\.(woff|woff2|tff|eots))

  - url: /icons
    static_dir: public/icons

# Test login option
  - url: /protected.html
    static_files: public/protected.html
    upload: public/protected.html
    login: required

  - url: /protected.html
    script: auto

# Home page handling
  - url: /
    static_files: public/index.html
    upload: public/index.html
    secure: always

# Support paths with a slash at the end
  - url: /(.+)/
    static_files: public/\1/index.html
    upload: public/(.+)/index.html

# Any left over we treat as a path
  - url: /(.+)
    static_files: public/\1/index.html
    upload: public/(.+)/index.html
