runtime: nodejs10
service: default
default_expiration: "1m"
handlers:
# Netlify CMS has a config.yml that needs to be served up
  - url: /(.*\.yml)
    mime_type: text/yaml
    static_files: public/\1
    secure: always
    upload: public/(.*\.yml)

  - url: /(.*\.js)
    mime_type: text/javascript
    static_files: public/\1
    secure: always
    upload: public/(.*\.js)

# Images and fonts
  - url: /(.*\.(gif|ico|jpeg|jpg|png|svg))
    static_files: public/\1
    secure: always
    upload: public/(.*\.(gif|ico|jpeg|jpg|png|svg))

# Fonts
  - url: /(.*\.(woff|woff2|tff|eot))
    static_files: public/\1
    secure: always
    upload: public/(.*\.(woff|woff2|tff|eots))

  - url: /icons
    static_dir: public/icons
    secure: always

# Protected page handling
  - url: /(.*)
    script: auto
    secure: always
