runtime: nodejs10
service: default
default_expiration: 60m
handlers:
  - url: /admin/(.*\.yml)
    mime_type: text/yaml
    static_files: public/admin/\1
    secure: always
    upload: public/admin/(.*\.yml)

  - url: /admin/cms.css
    mime_type: text/css
    static_files: public/admin/cms.css
    secure: always
    upload: public/admin/cms.css

  - url: /admin/
    expiration: 5m
    static_files: public/admin/index.html
    upload: public/admin/index.html
    http_headers:
      Content-Security-Policy: |-
        connect-src 'self' https://api.github.com; default-src 'self'; img-src 'self' data: https://*.githubusercontent.com; media-src https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';

  - url: /admin/index.html
    expiration: 5m
    static_files: public/admin/index.html
    upload: public/admin/index.html
    http_headers:
      Content-Security-Policy: |-
        connect-src 'self' https://api.github.com; default-src 'self'; img-src 'self' data: https://*.githubusercontent.com; media-src https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';

  - url: /admin/cms.js
    expiration: 30m
    mime_type: text/javascript
    static_files: public/admin/cms.js
    secure: always
    upload: public/admin/cms.js

  - url: /sw.js
    script: auto
    secure: always

  - url: /(.*\.js)
    expiration: 1d
    mime_type: text/javascript
    static_files: public/\1
    secure: always
    upload: public/(.*\.js)

# Protected content managed images and fonts (driven by CMS)
  - url: /assets/(.*\.(gif|ico|jpeg|jpg|png|svg))
    script: auto
    secure: always

# Online route for offline detection
  - url: /online
    expiration: 1d
    mime_type: text/plain
    static_files: public/online.txt
    secure: always
    upload: public/online.txt

# No need for protection for images and fonts driven from code repository
  - url: /(.*\.(gif|ico|jpeg|jpg|png|svg))
    expiration: 1d
    static_files: public/\1
    secure: always
    upload: public/(.*\.(gif|ico|jpeg|jpg|png|svg))

# Fonts
  - url: /(.*\.(woff|woff2|ttf|eot))
    expiration: 7d
    static_files: public/\1
    secure: always
    upload: public/(.*\.(woff|woff2|ttf|eots))

  - url: /icons
    expiration: 1d
    static_dir: public/icons
    secure: always

# Protected page handling
  - url: /(.*)
    script: auto
    secure: always
