runtime: nodejs10
service: default
default_expiration: 60m
handlers:
  - url: /admin/(.*\.yml)
    mime_type: text/yaml
    static_files: public/admin/\1
    secure: always
    upload: public/admin/(.*\.yml)

  - url: /admin/
    static_files: public/admin/index.html
    upload: public/admin/index.html
    http_headers:
      Content-Security-Policy-Report-Only: default-src 'self'; img-src 'self' data:; media-src https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';

  - url: /(sw.js)
    expiration: 1m
    mime_type: text/javascript
    static_files: public/\1
    secure: always
    upload: public/(.*\.js)

  - url: /(.*\.js)
    expiration: 1d
    mime_type: text/javascript
    static_files: public/\1
    secure: always
    upload: public/(.*\.js)

# Images and fonts
  - url: /(.*\.(gif|ico|jpeg|jpg|png|svg))
    expiration: 1d
    static_files: public/\1
    secure: always
    upload: public/(.*\.(gif|ico|jpeg|jpg|png|svg))

# Fonts
  - url: /(.*\.(woff|woff2|ttf|eot))
    expiration: 7d
    static_files: public/\1
    secure: always
    upload: public/(.*\.(woff|woff2|ttf|eots))

  - url: /icons
    expiration: 1d
    static_dir: public/icons
    secure: always

# Protected page handling
  - url: /(.*)
    script: auto
    secure: always
