runtime: nodejs10
service: default
default_expiration: 60m
handlers:
  - url: /admin/(.*\.yml)
    mime_type: text/yaml
    static_files: public/admin/\1
    secure: always
    upload: public/admin/(.*\.yml)

  - url: /admin/cms.css
    mime_type: text/css
    static_files: public/admin/cms.css
    secure: always
    upload: public/admin/cms.css

  - url: /admin/
    expiration: 5m
    static_files: public/admin/index.html
    upload: public/admin/index.html
    http_headers:
      Content-Security-Policy: |-
        connect-src 'self' blob: https://api.github.com https://upload.uploadcare.com; default-src 'self'; img-src 'self' data: blob: https://*.githubusercontent.com https://ucarecdn.com https://*.amazonaws.com; media-src https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';

  - url: /admin/index.html
    expiration: 5m
    static_files: public/admin/index.html
    upload: public/admin/index.html
    http_headers:
      Content-Security-Policy: |-
        connect-src 'self' blob: https://api.github.com https://upload.uploadcare.com; default-src 'self'; img-src 'self' data: blob: https://*.githubusercontent.com https://ucarecdn.com https://*.amazonaws.com; media-src https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';

  - url: /admin/cms.js
    expiration: 30m
    mime_type: text/javascript
    static_files: public/admin/cms.js
    secure: always
    upload: public/admin/cms.js

# Protected page handling
  - url: /(.*)
    script: auto
    secure: always
