runtime: nodejs10
default_expiration: "1m"
handlers:
  - url: /(.*\.json)
    mime_type: application/json
    static_files: public/\1
    upload: public/(.*\.json)

  - url: /(.*\.yml)
    mime_type: text/yaml
    static_files: public/\1
    upload: public/(.*\.yml)

  - url: /(.*\.js)
    mime_type: text/javascript
    static_files: public/\1
    upload: public/(.*\.js)

  - url: /(.*\.(gif|ico|jpeg|jpg|png))
    static_files: public/\1
    upload: public/(.*\.(gif|ico|jpeg|jpg|png))

  - url: /icons
    static_dir: public/icons

  - url: /
    static_files: public/index.html
    upload: public/index.html

  - url: /(.+)/
    static_files: public/\1/index.html
    upload: public/(.+)/index.html

  - url: /(.+)
    static_files: public/\1/index.html
    upload: public/(.+)/index.html
